'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8762
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Escritorio.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Commercial Assistant.
        '''</summary>
        Public ReadOnly Property AComercial() As String
            Get
                Return ResourceManager.GetString("AComercial", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Administrator.
        '''</summary>
        Public ReadOnly Property Admin() As String
            Get
                Return ResourceManager.GetString("Admin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open.
        '''</summary>
        Public ReadOnly Property CajaAbierta() As String
            Get
                Return ResourceManager.GetString("CajaAbierta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Closed.
        '''</summary>
        Public ReadOnly Property CajaCerrada() As String
            Get
                Return ResourceManager.GetString("CajaCerrada", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cashier.
        '''</summary>
        Public ReadOnly Property Cajero() As String
            Get
                Return ResourceManager.GetString("Cajero", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Married.
        '''</summary>
        Public ReadOnly Property Casado() As String
            Get
                Return ResourceManager.GetString("Casado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dated.
        '''</summary>
        Public ReadOnly Property ChequeDiferido() As String
            Get
                Return ResourceManager.GetString("ChequeDiferido", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Direct.
        '''</summary>
        Public ReadOnly Property ChequeDirecto() As String
            Get
                Return ResourceManager.GetString("ChequeDirecto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Savings Account.
        '''</summary>
        Public ReadOnly Property CuentaAhorro() As String
            Get
                Return ResourceManager.GetString("CuentaAhorro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Checking Account.
        '''</summary>
        Public ReadOnly Property CuentaCorriente() As String
            Get
                Return ResourceManager.GetString("CuentaCorriente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 0000.
        '''</summary>
        Public ReadOnly Property DefaultPin() As String
            Get
                Return ResourceManager.GetString("DefaultPin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Deposit.
        '''</summary>
        Public ReadOnly Property Deposito() As String
            Get
                Return ResourceManager.GetString("Deposito", resourceCulture)
            End Get
        End Property
        
        Public ReadOnly Property FSystems() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FSystems", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Manager.
        '''</summary>
        Public ReadOnly Property Gerente() As String
            Get
                Return ResourceManager.GetString("Gerente", resourceCulture)
            End Get
        End Property
        
        Public ReadOnly Property if_bank_building_532649() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_bank-building_532649", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property if_checks_87418() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_checks_87418", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property if_Client_Male_Light_80824() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_Client_Male_Light_80824", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property if_contact_new_23203() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_contact-new_23203", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property if_Money_Increase_379473() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_Money-Increase_379473", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property if_money_safe_box_532633() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_money-safe-box_532633", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property if_new_zoom_best_fit_23480() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_new-zoom-best-fit_23480", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property if_refresh_60202() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_refresh_60202", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property if_resolutions_16_897226() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_resolutions-16_897226", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property if_search_magnifying_glass_find_103857() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_search_magnifying_glass_find_103857", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property if_sign_up_49622() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_sign-up_49622", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to American Dollar.
        '''</summary>
        Public ReadOnly Property MonedaDolarUSD() As String
            Get
                Return ResourceManager.GetString("MonedaDolarUSD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Uruguayan Peso.
        '''</summary>
        Public ReadOnly Property MonedaPesoUYU() As String
            Get
                Return ResourceManager.GetString("MonedaPesoUYU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The client now has access to the account.
        '''</summary>
        Public ReadOnly Property MsgAgregarAcceso() As String
            Get
                Return ResourceManager.GetString("MsgAgregarAcceso", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error ocurred trying to give access to the account.
        '''</summary>
        Public ReadOnly Property MsgAgregarAccesoError() As String
            Get
                Return ResourceManager.GetString("MsgAgregarAccesoError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The workstation has been open.
        '''</summary>
        Public ReadOnly Property MsgCajaAbierta() As String
            Get
                Return ResourceManager.GetString("MsgCajaAbierta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The new workstation was added.
        '''</summary>
        Public ReadOnly Property MsgCajaCreada() As String
            Get
                Return ResourceManager.GetString("MsgCajaCreada", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The workstation was not able to open, check the inputs.
        '''</summary>
        Public ReadOnly Property MsgCajaNoAbierta() As String
            Get
                Return ResourceManager.GetString("MsgCajaNoAbierta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error has ocurred trying to add the new workstation.
        '''</summary>
        Public ReadOnly Property MsgCajaNoCreada() As String
            Get
                Return ResourceManager.GetString("MsgCajaNoCreada", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to close the account?.
        '''</summary>
        Public ReadOnly Property MsgCerrarCuenta() As String
            Get
                Return ResourceManager.GetString("MsgCerrarCuenta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The check has been payed.
        '''</summary>
        Public ReadOnly Property MsgChequeCobrado() As String
            Get
                Return ResourceManager.GetString("MsgChequeCobrado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error has ocurred trying to pay the check.
        '''</summary>
        Public ReadOnly Property MsgChequeCobradoError() As String
            Get
                Return ResourceManager.GetString("MsgChequeCobradoError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The new checkbook was added to the account.
        '''</summary>
        Public ReadOnly Property MsgChequeraNueva() As String
            Get
                Return ResourceManager.GetString("MsgChequeraNueva", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error ocurred trying to add the new checkbook.
        '''</summary>
        Public ReadOnly Property MsgChequeraNuevaError() As String
            Get
                Return ResourceManager.GetString("MsgChequeraNuevaError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The client has been updated.
        '''</summary>
        Public ReadOnly Property MsgClienteActualizado() As String
            Get
                Return ResourceManager.GetString("MsgClienteActualizado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error has ocurred trying to update the client.
        '''</summary>
        Public ReadOnly Property MsgClienteActualizadoError() As String
            Get
                Return ResourceManager.GetString("MsgClienteActualizadoError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The client already exist.
        '''</summary>
        Public ReadOnly Property MsgClienteExiste() As String
            Get
                Return ResourceManager.GetString("MsgClienteExiste", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Client does not exist.
        '''</summary>
        Public ReadOnly Property MsgClienteNoExiste() As String
            Get
                Return ResourceManager.GetString("MsgClienteNoExiste", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The account was re-open.
        '''</summary>
        Public ReadOnly Property MsgCuentaAbierta() As String
            Get
                Return ResourceManager.GetString("MsgCuentaAbierta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The account had been closed.
        '''</summary>
        Public ReadOnly Property MsgCuentaCerrada() As String
            Get
                Return ResourceManager.GetString("MsgCuentaCerrada", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error has ocurred trying to close the account.
        '''</summary>
        Public ReadOnly Property MsgCuentaCerradaError() As String
            Get
                Return ResourceManager.GetString("MsgCuentaCerradaError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The deposit has been succesful.
        '''</summary>
        Public ReadOnly Property MsgDeposito() As String
            Get
                Return ResourceManager.GetString("MsgDeposito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error has ocurred trying to deposit the money.
        '''</summary>
        Public ReadOnly Property MsgDepositoError() As String
            Get
                Return ResourceManager.GetString("MsgDepositoError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Employee has been assigned to the branch.
        '''</summary>
        Public ReadOnly Property MsgEmpleadoAsignadoSucursal() As String
            Get
                Return ResourceManager.GetString("MsgEmpleadoAsignadoSucursal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error has ocurred trying to add the employee to the branch.
        '''</summary>
        Public ReadOnly Property MsgEmpleadoNoAsignadoSucursal() As String
            Get
                Return ResourceManager.GetString("MsgEmpleadoNoAsignadoSucursal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The exchange value has been updated.
        '''</summary>
        Public ReadOnly Property MsgMonedaCambiada() As String
            Get
                Return ResourceManager.GetString("MsgMonedaCambiada", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error has ocurred trying to update the exchange value.
        '''</summary>
        Public ReadOnly Property MsgMonedaNoCambiada() As String
            Get
                Return ResourceManager.GetString("MsgMonedaNoCambiada", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New account created.
        '''</summary>
        Public ReadOnly Property MsgNuevaCuenta() As String
            Get
                Return ResourceManager.GetString("MsgNuevaCuenta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error has ocurred trying to create the new account.
        '''</summary>
        Public ReadOnly Property MsgNuevaCuentaError() As String
            Get
                Return ResourceManager.GetString("MsgNuevaCuentaError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New client created.
        '''</summary>
        Public ReadOnly Property MsgNuevoCliente() As String
            Get
                Return ResourceManager.GetString("MsgNuevoCliente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error has ocurred trying to create the new client.
        '''</summary>
        Public ReadOnly Property MsgNuevoClienteError() As String
            Get
                Return ResourceManager.GetString("MsgNuevoClienteError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The pin was updated.
        '''</summary>
        Public ReadOnly Property MsgNuevoPin() As String
            Get
                Return ResourceManager.GetString("MsgNuevoPin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error has ocurred trying to update the pin.
        '''</summary>
        Public ReadOnly Property MsgNuevoPinError() As String
            Get
                Return ResourceManager.GetString("MsgNuevoPinError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The pin is invalid.
        '''</summary>
        Public ReadOnly Property MsgPinIncorrecto() As String
            Get
                Return ResourceManager.GetString("MsgPinIncorrecto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The client do not have access to this account anymore.
        '''</summary>
        Public ReadOnly Property MsgQuitarAcceso() As String
            Get
                Return ResourceManager.GetString("MsgQuitarAcceso", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error ocurred trying to revoke access to the account.
        '''</summary>
        Public ReadOnly Property MsgQuitarAccesoError() As String
            Get
                Return ResourceManager.GetString("MsgQuitarAccesoError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The withdraw has been succesful.
        '''</summary>
        Public ReadOnly Property MsgRetiro() As String
            Get
                Return ResourceManager.GetString("MsgRetiro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error has ocurred trying to withdraw the money.
        '''</summary>
        Public ReadOnly Property MsgRetiroError() As String
            Get
                Return ResourceManager.GetString("MsgRetiroError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The branch has been updated.
        '''</summary>
        Public ReadOnly Property MsgSucursalActualizada() As String
            Get
                Return ResourceManager.GetString("MsgSucursalActualizada", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New branch added.
        '''</summary>
        Public ReadOnly Property MsgSucursalAgregada() As String
            Get
                Return ResourceManager.GetString("MsgSucursalAgregada", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error has ocurred trying to update the branch.
        '''</summary>
        Public ReadOnly Property MsgSucursalNoActualizada() As String
            Get
                Return ResourceManager.GetString("MsgSucursalNoActualizada", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error has ocurred trying to add the new branch.
        '''</summary>
        Public ReadOnly Property MsgSucursalNoAgregada() As String
            Get
                Return ResourceManager.GetString("MsgSucursalNoAgregada", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The transfer was succesful.
        '''</summary>
        Public ReadOnly Property MsgTransferencia() As String
            Get
                Return ResourceManager.GetString("MsgTransferencia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error has ocurred trying to transfer the money.
        '''</summary>
        Public ReadOnly Property MsgTransferenciaError() As String
            Get
                Return ResourceManager.GetString("MsgTransferenciaError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Withdraw.
        '''</summary>
        Public ReadOnly Property Retiro() As String
            Get
                Return ResourceManager.GetString("Retiro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Single.
        '''</summary>
        Public ReadOnly Property Soltero() As String
            Get
                Return ResourceManager.GetString("Soltero", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Transfer.
        '''</summary>
        Public ReadOnly Property Transferencia() As String
            Get
                Return ResourceManager.GetString("Transferencia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Default Value.
        '''</summary>
        Public ReadOnly Property ValorDefecto() As String
            Get
                Return ResourceManager.GetString("ValorDefecto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Widow.
        '''</summary>
        Public ReadOnly Property Viudo() As String
            Get
                Return ResourceManager.GetString("Viudo", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
